name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub actions
on:
  - push
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node 14
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: check bats version
        run: |
          npm install -g bats
          bats -v

      - name: visualize repo
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,node_modules"
