name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub actions
on:
  - push
  - workflow_dispatch

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node 14
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: check bats version
        run: |
          npm install -g bats
          bats -v

      - name: visualise repo
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,node_modules"
          output_file: "docs/diagram.svg"
          should_push: true

      - name: dump GitHub context
        id: github_context_step
        run: |
          echo 'github context'
          echo '${{ toJSON(github) }}'

          echo 'job context'
          echo '${{ toJSON(job) }}'

          echo 'steps context'
          echo '${{ toJSON(steps) }}'

          echo 'runner context'
          echo '${{ toJSON(runner) }}'

          echo 'strategy context'
          echo '${{ toJSON(strategy) }}'

          echo 'matrix context'
          echo '${{ toJSON(matrix) }}'

      - name: sleep a bit
        run: sleep 5
